"""Add place_id to user

Revision ID: 7c40f18438df
Revises: d4867f3a4c0a
Create Date: 2024-02-03 21:31:25.252036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c40f18438df'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_id', table_name='item')
    op.add_column('user', sa.Column('place_id', sa.UUID(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_user_id', table_name='user')
    op.create_foreign_key(None, 'user', 'place', ['place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'place_id')
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    # ### end Alembic commands ###
